// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMatchData(ctx context.Context, arg CreateMatchDataParams) (MatchDatum, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMatchData(ctx context.Context, id int64) error
	FindUserByEmail(ctx context.Context, email string) (User, error)
	GetFiles(ctx context.Context, createdByID int64) ([]File, error)
	GetMatchData(ctx context.Context, createdByID int64) ([]MatchDatum, error)
	GetMatchDataById(ctx context.Context, id int64) (MatchDatum, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, id int64) (User, error)
	UpdateMatchData(ctx context.Context, arg UpdateMatchDataParams) (MatchDatum, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
